### PR TITLE
Attempt 1

### PR DESCRIPTION
**Pull request by Chummel**

### CODE REVIEW

**Comment by Chummel** [comment]
I'm a bit confused, I thought my code looked correct and I've checked the spacing, spelling, all that, yet it's still incorrect.

**Comment by halfaro1** [comment]
@Chummel double check your punctuation on the exception message, then it should pass!

**Comment by Chummel** [comment]
Got it. Thank you Mr. Alfaro!

**Comment by halfaro1** [comment]
@Chummel my pleasure - good work

**Pull request closed without merging**
